### ISSUE TITLE
Batch downloading fasta files from a list of Accession#

### ISSUE THREAD

**Issue by kwnamhang** [AstrobioMike/bioinf_tools#3]
Hi Mike,

Thanks for making this tool - exactly what I'm looking for.

I'm trying to batch download fasta files from a list of Genbank Accessions that I've made as .csv file.

However, when I try to run the command, I get the following:

~/Downloads$ bit-dl-ncbi-assemblies -w list.csv -f fasta -j 10

    Targeting 157 genomes in fasta format.

    Downloading ncbi assembly summaries to be able to construct ftp links...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
curl: (28) Connection timed out after 30000 milliseconds
Warning: Transient problem: timeout Will retry in 1 seconds. 10 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
curl: (28) Connection timed out after 30000 milliseconds
Warning: Transient problem: timeout Will retry in 2 seconds. 9 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:29 --:--:--     0
curl: (28) Connection timed out after 30000 milliseconds
Warning: Transient problem: timeout Will retry in 4 seconds. 8 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
curl: (28) Connection timed out after 30000 milliseconds
Warning: Transient problem: timeout Will retry in 8 seconds. 7 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
curl: (28) Connection timed out after 30000 milliseconds
Warning: Transient problem: timeout Will retry in 16 seconds. 6 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
curl: (28) Connection timed out after 30000 milliseconds
Warning: Transient problem: timeout Will retry in 32 seconds. 5 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
curl: (28) Connection timed out after 30000 milliseconds
Warning: Transient problem: timeout Will retry in 64 seconds. 4 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:29 --:--:--     0
curl: (28) Connection timed out after 30000 milliseconds
Warning: Transient problem: timeout Will retry in 128 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
curl: (28) Connection timed out after 30001 milliseconds
Warning: Transient problem: timeout Will retry in 256 seconds. 2 retries left.

Is there an easy fix to this? Is it because I'm requesting from .csv rather than .txt file? Any other parameters I need to set?

Many thanks for your help!

**Comment by kwnamhang** [comment]
Thanks for your prompt reply!

I can confirm that the first command you gave works - downloading via ftp.

Also, I've now re-run my original command "bit-dl-ncbi-assemblies -w list.csv -f fasta -j 10" and it's now downloading fine via ftp!

As you say, it may be that my work network doesn't allow ftp transfer (based within a hospital laboratory). Seems to work fine over my home network.

I'll try the http-based command when I'm next at work. Ideally, would be great to be able to use your tool at work also.

Thanks again for your help and making this tool :+1:

**Comment by AstrobioMike** [comment]
Oh great :)

I will add the capability to be able to do it through http tomorrow and let you know when it’s in, either way the option will be helpful to have, and hopefully it will work on your work network🤞

**Comment by kwnamhang** [comment]
Hmmm... perhaps I spoke too soon... I thought it began downloading but when it finished, says none of the accessions were found? I've manually checked the accessions, and they are definitely searchable on NCBI. Not sure what's the issue. Sorry to bug you!

bit-dl-ncbi-assemblies -w list.txt -f fasta -j 10

    Targeting 157 genomes in fasta format.

    Downloading ncbi assembly summaries to be able to construct ftp links...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  238M  100  238M    0     0   216k      0  0:18:47  0:18:47 --:--:--  297k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 60.2M  100 60.2M    0     0   200k      0  0:05:07  0:05:07 --:--:--  154k


     ******************************* NOTICE *******************************  
		  157 input accessions were not found at NCBI.

		  Written to "NCBI-accessions-not-found.txt".
     ********************************************************************** 

	  Remaining total targets: 0

**Comment by AstrobioMike** [comment]
Interesting, can you email me the input accessions file so I can see if I can recreate it? MikeLee@bmsis.org

**Comment by AstrobioMike** [comment]
Oh and I forgot about this tool that fortunately I noted at the top of that page I just linked to, maybe this can grab what you’re looking for :)

https://github.com/kblin/ncbi-acc-download
