### ISSUE TITLE
Conda bit python requirements

### ISSUE THREAD

**Issue by genignored** [AstrobioMike/bioinf_tools#4]
Hi,
was trying to install bit into an environment I already had installed with Python=3.8, and bit won't install, due to the requirements:

 - bit -> python[version='>=3.7,<3.8.0a0']

Not sure if there is a major bug or reason bit won't work with >3.7, but wanted to see if this was something that could be corrected.

**Comment by AstrobioMike** [comment]
Hi there :)

Sorry, I actually looked into this recently, checking if I could loosen it, but the 3.7 was a restriction retained by one of the packages in there. (Though I don't remember which one off the top of my head at the moment)

I know it's not ideal for quick-use bioinformatics scripts, but I've let it grow too much as I've added more things I needed, and am now in this weird place right now with it, where it's not as flexible as I'd like it to be, ha
